### PR TITLE
it fixes redirection issue with Twallet URL

### PR DESCRIPTION
**Pull request by lcs86-dev**
This PR addresses a redirection issue with the Twallet URL

### CODE REVIEW

**Review by gregnazario — APPROVED** [review]

**Review by 0xmaayan — COMMENTED** [review]
Please update changelog, so we can release a new version, by running `pnpm run changeset`

**Comment by lcs86-dev** [comment]
> Please update changelog, so we can release a new version, by running `pnpm run changeset`

I've updated the changelog and pushed the changes. Thanks for letting me know about it.
Sorry for any inconvenience this might have caused for the release.

**Review by 0xmaayan — APPROVED** [review]

**Comment by 0xmaayan** [comment]
@lcs86-dev build is failing. You should run `pnpm i` (on the adapter root folder) to update `package-lock.json`

**Comment by lcs86-dev** [comment]
> @lcs86-dev build is failing. You should run `pnpm i` (on the adapter root folder) to update `package-lock.json`

I just updated the package-lock.json file and ran pnpm run build in the root folder. And the build failed with the following message: 'Type '"1.1.0"' is not assignable to type '"1.0.0"'. Should the version of the Twallet class be changed to 1.1.0?

Screen Shot 2024-06-04 at 11 42 27 AM

**Comment by 0xmaayan** [comment]
oh I think it is because of a recent package upgrade.

could you fix the version here https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/package.json#L53 to `"@aptos-labs/wallet-standard": "0.0.11"` (remove the `^`) and then run `pnpm i` and `pnpm turbo run build`

sorry about that

**Comment by lcs86-dev** [comment]
> oh I think it is because of a recent package upgrade.
> 
> could you fix the version here https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/package.json#L53 to `"@aptos-labs/wallet-standard": "0.0.11"` (remove the `^`) and then run `pnpm i` and `pnpm turbo run build`
> 
> sorry about that

I updated the package.json file to set "@aptos-labs/wallet-standard" to "0.0.11" (removing the ^). After that, I ran pnpm i and pnpm turbo run build. Unfortunately, the build still fails.

Screen Shot 2024-06-04 at 12 45 21 PM

**Comment by 0xmaayan** [comment]
> > oh I think it is because of a recent package upgrade.
> 
> > 
> 
> > could you fix the version here https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/packages/wallet-adapter-core/package.json#L53 to `"@aptos-labs/wallet-standard": "0.0.11"` (remove the `^`) and then run `pnpm i` and `pnpm turbo run build`
> 
> > 
> 
> > sorry about that
> 
> 
> 
> I updated the package.json file to set "@aptos-labs/wallet-standard" to "0.0.11" (removing the ^). After that, I ran pnpm i and pnpm turbo run build. Unfortunately, the build still fails.
> 
> 
> 
> Screen Shot 2024-06-04 at 12 45 21 PM

oh ok @lcs86-dev , I think you should update the twallet package to use a fix `0.0.11` version of the wallet-standard package instead of `latest`. 

We are currently working on changing the wallet-standard package due to some feedbacks we got

**Comment by lcs86-dev** [comment]
Now, the @atomrigslab/aptos-wallet-adapter depends on version 0.0.11 of wallet-standard.
And the build completes successfully. Thank you for your help

**Pull request merged**
