### PR TITLE
Add Trust Wallet

### PR DESCRIPTION
**Pull request by rsrbk**

### CODE REVIEW

**Comment by 0xmaayan** [comment]
@rsrbk , running `npm i @trustwallet/aptos-wallet-adapter` doesnt build a `dist` dir and then can't be imported on the app

**Comment by rsrbk** [comment]
@0xmaayan how do I fix it? i followed all steps in https://github.com/aptos-labs/wallet-adapter-plugin-template

**Comment by 0xmaayan** [comment]
@rsrbk what happens when you run 'npm publish --dry-run' in you project? 
do you have a repo with your code? I can help take a look.

**Comment by 0xmaayan** [comment]
@rsrbk just tested it, looks like you need to build it and then publish it, so you should do 
- `npm install`
- `npm run build` 
- `npm publish` (you can run `npm publish --dry-run` to see what would be published) 

Added it to the readme on the main repo, thanks!
https://github.com/aptos-labs/wallet-adapter-plugin-template#publish-as-a-package

**Comment by rsrbk** [comment]
@0xmaayan just published a new version (0.1.4) with `npm run build`, could you check please?

**Pull request merged**
