### PR TITLE
Add FaceWallet Aptos adapter plugin 

### PR DESCRIPTION
**Pull request by rasplarry**

### CODE REVIEW

**Comment by 0xmaayan** [comment]
@raspLarry build is failing, please make sure you follow https://github.com/aptos-labs/aptos-wallet-adapter/blob/main/CONTRIBUTING.md#creating-a-pull-request

**Comment by rasplarry** [comment]
@0xmaayan 
After merge upstream main, I've done two commands then succeeded.
- cleared all node modules and builds.
- `pnpm install` from root.
- `pnpm turbo run build` from root.

But on the github actions it still fails. I will figure it why then request your review again!

**Comment by rasplarry** [comment]
@0xmaayan 
Github actions succeeded on forked repo! Please review mine. Thank you :)

**Review by 0xmaayan — APPROVED** [review]

**Comment by rasplarry** [comment]
@0xmaayan 
Hello. I am really happy that our FaceWallet has been merged to the official Aptos Adapter repo!
Can I please know when it will be deployed on your sample Github Pages?

**Comment by 0xmaayan** [comment]
> @0xmaayan Hello. I am really happy that our FaceWallet has been merged to the official Aptos Adapter repo! Can I please know when it will be deployed on your sample Github Pages?

it is deployed. looks like there are some errors on connect.

**Pull request merged**
