### PR TITLE
feat: add TokenPocket wallet adapter

### PR DESCRIPTION
**Pull request by chendatony31**
Add TokenPocket aptos wallet adapter

### CODE REVIEW

**Comment by 0xmaayan** [comment]
was looking at the TokenPocket plugin implementation https://www.npmjs.com/package/@tp-lab/aptos-wallet-adapter?activeTab=explore

Are these correct?

1. window key should be `aptos`?
2. `providerName` should be `aptos`?

**Comment by chendatony31** [comment]
Yes, as we are a mobile wallet, so I think there would not be a conflict with other extensions. What's more, I think there should have an interface such as `installed` that can be implemented by the wallets themselves. For example we have `aptos.isTokenPocket` it can perfectly be detected if TokenPocket is installed.

**Comment by 0xmaayan** [comment]
I see. The problem with that is that the window `aptos` key used by Petra wallet, so when using TokenPocket it would try to open and connect to Petra on a web app. 

We have a plan to add a better support to mobile wallets and to try and make sense with all the different platforms wallets are using.

For now, I would suggest to use a different key (maybe `tokenPocket`) if it doesn't really matter to you and to make sure there would be no conflicts

**Comment by chendatony31** [comment]
Using `aptos` is by design, as most dapps have integrated with Petra. to be compatible with most dapp we have to use it too. Such as `ethereum` object using by metamask.

We will add other key just like you said maybe `tokenPocket` next month, but we will keep `aptos` either.

**Comment by 0xmaayan** [comment]
having all dapps using `aptos` is a bad design and exactly what the adapter solves - support different wallets that use a unique and different namespace (i.e window key). This helps to avoid conflicts and/or collisions (that happened in different networks).

`aptos` key was first used by `Aptos Wallet` which today is `Petra` but in reality shouldn't be used by anyone. Still, `Petra` uses its own namespace https://www.npmjs.com/package/petra-plugin-wallet-adapter?activeTab=explore

**Comment by chendatony31** [comment]
Yes, I agree different wallets should have their own namespace, that is why we are going to add `tokenpocket` as our namespace, but as a dapp developer, including so many wallets' packages is also not a good idea. In particular, the interfaces implemented are basically the same.

I think using wallets' different own namespace is a option. but `aptos` should as a backward option to interact with any other unknown aptos wallets. Just like `ethereum` for EVM chains. To void conflicts they can detect `window.aptos` before injecting their own `aptos`.  That's what most EVM extension wallets have done.

**Comment by 0xmaayan** [comment]
@chendatony31 please resolve conflicts

**Comment by chendatony31** [comment]
> @chendatony31 please resolve conflicts

Done

**Comment by chendatony31** [comment]
Hi @0xmaayan, We have change our namespace into `tokenpocket`

**Review by 0xmaayan — APPROVED** [review]

**Pull request merged**
